sudo: required
language: bash
services:
  - docker
before_script:
  - docker build --tag keboola/docker-r-jupyter .
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
